package cridit.machineSide.events;

import java.util.Locale;

public enum EventType {
    CALCULATION_ACCURACY,
    CONSISTENCY,
    ASSUMPTION_TRANSPARENCY,
    TRACEABILITY,
    AUDITABILITY,
    SOURCE_GROUNDING,
    RISK_COMPLETENESS,
    PROFESSIONAL_BOUNDARIES,
    CRITERIA_TRANSPARENCY,
    EXPLAINABILITY,
    FAIRNESS,
    CLASSIFICATION_ACCURACY,
    FEEDBACK_QUALITY,
    TONE_PROFESSIONALISM,
    HUMAN_OVERSIGHT,
    EFFICIENCY,
    CORRECTION_ABILITY,
    RELIABILITY,
    CITATION_ACCURACY,
    TRANSPARENCY,
    BIAS_FAIRNESS,
    PRIVACY_SECURITY,
    ACCOUNTABILITY,
    UNCERTAINTY_LIMITS;

    public String key() {
        return name().toLowerCase(Locale.ROOT);
    }
}
